apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
      volumeMounts:
      - mountPath: /etc/nginx/conf.d
        name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    nodePort: 30080
  type: NodePort