apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/50 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: node:9.5-alpine
            args:
            - /bin/sh
            - -c
            - echo world!
          restartPolicy: Never